name: GitHub Metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write   
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:

          filename: github-metrics.svg

          token: ${{ secrets.METRICS_TOKEN }}

          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: pranauvskandhan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

         
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_followup: yes
          plugin_followup_sections: user, repositories

          
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_lines: yes
