# .github/workflows/metrics.yml
name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # run twice a day
  workflow_dispatch:

# give GitHub Actions permission to write files
permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Generate profile metrics (no-Docker)
        uses: lowlighter/metrics@latest
        with:
          use_prebuilt: yes
          filename: github-metrics.svg

          # your personal classic PAT for reading stats
          token: ${{ secrets.METRICS_TOKEN }}

          # built-in token for committing svg
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          committer_message: "chore: update github-metrics.svg"

          user: pranauvskandhan
          template: classic
          config_timezone: Asia/Kolkata

          base: header, activity, repositories, metadata

          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_followup: yes
          plugin_followup_sections: user, repositories

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_charts: yes

          retries: 2
          retries_delay: 20
